app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField
from wtforms.validators import DataRequired
from flask_pagedown.fields import PageDownField


class PostForm(FlaskForm):
    body = PageDownField("What's on your mind?Tell that", validators=[DataRequired()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    body = StringField('', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/post/__init__.py
from flask import Blueprint

post = Blueprint("post", __name__)

from . import views

app/post/views.py
from flask import render_template, redirect, url_for, request, \
    current_app, make_response, flash, abort
from flask_login import current_user, login_required
from . import post
from .forms import PostForm, CommentForm
from ..models import Post, Comment, Permission
from .. import db


@post.route('/', methods=['GET', 'POST'])
def show_posts():
    form = PostForm()
    if current_user.can(Permission.WRITE) and form.validate_on_submit():
        post = Post(body=form.body.data, author=current_user._get_current_object())
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('.show_posts'))

    page = request.args.get('page', 1, type=int)
    show_followed = False

    if current_user.is_authenticated:
        show_followed = bool(request.cookies.get('show_followed', ''))
    if show_followed:
        query = current_user.followed_posts
    else:
        query = Post.query
    pagination = query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('post/show_posts.html', form=form, posts=posts,
                           pagination=pagination, show_followed=show_followed)


@post.route('/<int:id>', methods=['GET', 'POST'])
def show_post(id):
    post = Post.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been published.')
        return redirect(url_for('post.show_post', id=post.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (post.comments.count() - 1) // \
               current_app.config['FLASKY_COMMENTS_PER_PAGE'] + 1
    pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    return render_template('post/single_post.html', posts=[post],
                           form=form, comments=comments, pagination=pagination)




@post.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author and \
            not current_user.can(Permission.ADMIN):
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        db.session.add(post)
        db.session.commit()
        flash('The post has been updated.')
        return redirect(url_for('post.show_post', id=post.id))
    form.body.data = post.body
    return render_template('post/edit_post.html', form=form)

@post.route('/all')
@login_required
def show_all():
    resp = make_response(redirect(url_for('post.show_posts')))
    resp.set_cookie('show_followed', '', max_age=30*24*60*60)  # 30 days
    return resp


@post.route('/followed')
@login_required
def show_followed():
    resp = make_response(redirect(url_for('post.show_posts')))
    resp.set_cookie('show_followed', '1', max_age=30*24*60*60)  # 30 days
    return resp

app/templates/post/edit_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Facebook - Edit Post{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Post</h1>
</div>
<div>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/post/list_comments.html
<ul class="comments">
    {% for comment in comments %}
    <li class="comment">
        <div class="comment-thumbnail">
            <a href="{{ url_for('profile.show_profile', username=comment.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ comment.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="comment-content">
            <div class="comment-date">{{ moment(comment.timestamp).fromNow() }}</div>
            <div class="comment-author"><a href="{{ url_for('profile.show_profile', username=comment.author.username) }}">{{ comment.author.username }}</a></div>
            <div class="comment-body">
                {% if comment.disabled %}
                <p></p><i>This comment has been disabled by a moderator.</i></p>
                {% endif %}

                {% if moderate or not comment.disabled %}
                    {% if comment.body_html %}
                    {{ comment.body_html | safe }}
                    {% else %}
                    {{ comment.body }}
                    {% endif %}
                {% endif %}
            </div>

            {% if moderate %}
                <br>
                {% if comment.disabled %}
                <a class="btn btn-default btn-xs" href="{{ url_for('main.moderate_enable', id=comment.id, page=page) }}">Enable</a>
                {% else %}
                <a class="btn btn-danger btn-xs" href="{{ url_for('main.moderate_disable', id=comment.id, page=page) }}">Disable</a>
                {% endif %}
            {% endif %}
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/post/list_posts.html
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="profile-thumbnail">
            <a href="{{ url_for('profile.show_profile', username=post.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ post.author.gravatar(size=40) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{ moment(post.timestamp).fromNow() }}</div>
            <div class="post-author">
            <a href="{{ url_for('profile.show_profile', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
        </div>
            <div class="post-body">
            {% if post.body_html %}
                {{ post.body_html | safe }}
            {% else %}
                {{ post.body }}
            {% endif %}
        </div>
            <div class="post-footer">
                {% if current_user == post.author %}
                <a href="{{ url_for('post.edit_post', id=post.id) }}">
                    <span class="label label-primary">Edit</span>
                </a>
                {% elif current_user.is_administrator() %}
                <a href="{{ url_for('post.edit_post', id=post.id) }}">
                    <span class="label label-danger">Edit [Admin]</span>
                </a>
                {% endif %}

             
                <a href="{{ url_for('post.show_post', id=post.id) }}#comments">
                    <span class="label label-primary">{{ post.comments.count() }} Comments</span>
                </a>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/post/show_posts.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Facebook - {{ current_user.username }}{% endblock %}

{% block page_content %}
<div>
    {% if current_user.can(Permission.WRITE) %}
    {{ wtf.quick_form(form) }}
    {% endif %}
</div>

<div class="post-tabs">
    <ul class="nav nav-tabs">
        <li {% if not show_followed %} class="active"{% endif %}><a href="{{ url_for('post.show_all') }}">All</a></li>
        {% if current_user.is_authenticated %}
        <li {% if show_followed %} class="active"{% endif %}><a href="{{ url_for('post.show_followed') }}">Followers</a></li>
        {% endif %}
    </ul>
    {% include 'post/list_posts.html' %}
</div>

<div>
    {% if pagination %}
    <div class="pagination">
        {{ macros.pagination_widget(pagination, 'post.show_posts') }}
    </div>
</div>
{% endif %}
{% endblock %}

app/templates/post/single_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Facebook - Post{% endblock %}

{% block page_content %}
{% include 'post/list_posts.html' %}

<h4 id="comments">Comments</h4>
{% if current_user.can(Permission.COMMENT) %}
<div class="comment-form">
    {{ wtf.quick_form(form) }}
</div>
{% endif %}
{% include 'post/list_comments.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, 'post.show_post', fragment='#comments', id=posts[0].id) }}
</div>
{% endif %}
{% endblock %}